services:
  zhihu_bot:
    build: .
    container_name: zhihu_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./save_zhihu_activity:/app/save_zhihu_activity
      - ./zhihu_articles.db:/app/zhihu_articles.db
      - ./state.json:/app/state.json:ro
